name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Change this to 'main' if you're using a 'main' branch
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18  # Use the Node.js version compatible with your project

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build

    - name: Remove symlinks (if any)
      run: find ./dist -type l -exec rm -f {} \;

    - name: Upload build output
      uses: actions/upload-artifact@v4
      with:
        name: github-pages
        path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
      with:
        artifact_name: github-pages
